my_site/my_site/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from my_site import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('site_app.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
]
urlpatterns += i18n_patterns(
    path('', include('site_app.urls')),
)



if settings.DEBUG:
    import debug_toolbar.urls
    urlpatterns = [
        path('__debug__/', include('debug_toolbar.urls')),
    ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_site/site_app/urls.py
from django.urls import path
from site_app.views import *

app_name = 'site_app'
urlpatterns = [
    path('', index, name='index'),
    path('download_cv/', download_cv, name='downloadcv'),
    path('skills/', SkillsView.as_view(), name='skills'),
    path('contacts/', ContactsView.as_view(), name='contacts'),
    path('portfolio/', portfolio, name='portfolio'),


]

my_site/site_app/models.py
import datetime

from django.core import validators
from django.core.validators import RegexValidator
from django.db import models

YEAR_CHOICES = [(r, r) for r in range(1984, datetime.date.today().year + 1)]
# Create your models here.

class MainInfo(models.Model):
    fio = models.CharField(max_length=50, verbose_name='ПІБ')
    slug = models.SlugField(max_length=100, unique=True, verbose_name='URL', db_index=True)
    position = models.CharField(max_length=50, verbose_name='Вакансія')
    about = models.TextField(verbose_name='Про себе')
    work_hour = models.ManyToManyField('WorkHours', verbose_name='Ступінь зайнятості', related_query_name='info')
    age = models.IntegerField(verbose_name='Вік')
    birthday = models.DateField(verbose_name='Дата народження')
    phone = models.CharField(max_length=18, verbose_name='Телефон')
    location_sity = models.ManyToManyField('Locations_Sity', verbose_name='Місто', related_query_name='info')
    location_country = models.ManyToManyField('Locations_Country', verbose_name='Країна', related_query_name='info')
    email = models.EmailField(verbose_name='Пошта')
    languages = models.ManyToManyField('Languages', verbose_name='Мова', related_query_name='info')
    workplaces = models.ManyToManyField('WorkPlaces', verbose_name='Попередні місця роботи', related_query_name='info')
    interests = models.ManyToManyField('Interests', verbose_name='Захоплення', related_query_name='info')
    educations = models.ManyToManyField('Educations', verbose_name='Освіта', related_query_name='info')
    whyme= models.ManyToManyField('WhyMe', verbose_name='Чому я', related_query_name='info')
    skills = models.ManyToManyField('Skills', verbose_name='Вміння', related_query_name='info')
    photo = models.ImageField(upload_to="workers_foto/", verbose_name="Фото")
    published = models.DateTimeField(auto_now_add=True, verbose_name='Дата публікації')

    objects = models.Manager()

    class Meta:
        verbose_name = 'Резюме'
        verbose_name_plural = 'Резюме'
        ordering = ['-published']

    def __str__(self):
        return self.fio


class WorkHours(models.Model):
    KINDS = (
        ('f', 'Повна занятість'),
        ('h', 'Часткова занятість'),
        ('o', 'Віддалена праця'),
        ('a', 'All day'),
        ('p', 'Part-time employment'),
        ('r', 'Remote working'),
        (None, 'Оберіть ступінь')
    )

    hours = models.CharField(max_length=1, choices=KINDS, default='f')
    objects = models.Manager()

    class Meta:
        verbose_name = 'Ступінь зайнятості'
        verbose_name_plural = 'Ступені зайнятості'

    def __str__(self):
        return f'{self.hours}'


class Locations_Sity(models.Model):
    sity = models.CharField(max_length=25, verbose_name='Місто')
    objects = models.Manager()

    class Meta:
        verbose_name = 'Місто'
        verbose_name_plural = 'Міста'

    def __str__(self):
        return f'{self.sity}'


class Locations_Country(models.Model):
    country = models.CharField(max_length=25, verbose_name='Країна')
    objects = models.Manager()

    class Meta:
        verbose_name = 'Країна'
        verbose_name_plural = 'Країни'

    def __str__(self):
        return f'{self.country}'


class Languages(models.Model):
    KIND = (
        ('ua', 'Українська'),
        ('en', 'Англійська'),
        ('ru', 'Російська'),
        ('ua-en', 'Ukranian'),
        ('en-en', 'English'),
        (None, 'Оберіть мову'),
    )

    KIND_L = (
        ('low', 'Низький'),
        ('medium', 'Середній'),
        ('high', 'Високий'),
        ('native', 'Рідна мова'),
        ('A', 'Beginner'),
        ('B', 'Average'),
        ('C', 'Advanced'),
        ('I', 'Fluent'),
        (None, 'Оберіть рівень'),
    )

    language = models.CharField(max_length=5, verbose_name='Мова', choices=KIND)
    level = models.CharField(max_length=6, verbose_name='Рівень', choices=KIND_L)

    objects = models.Manager()

    class Meta:
        verbose_name = 'Мова'
        verbose_name_plural = 'Мови'

    def __str__(self):
        return f'{self.language} - {self.level}'


class Interests(models.Model):
    interest = models.CharField(max_length=25, verbose_name='Захоплення')

    objects = models.Manager()

    class Meta:
        verbose_name = 'Захоплення'
        verbose_name_plural = 'Захоплення'

    def __str__(self):
        return self.interest


class Educations(models.Model):
    KIND_L = (
        ('so', 'Середньо-освітний'),
        ('st', 'Середньо-технічний'),
        ('nhl', 'Неповна вища освіта'),
        ('hl', 'Вища освіта'),
        ('univer', 'Master\'s degree'),
        ('m', 'Магістр'),
        ('kds', 'Кандидат у доктора наук'),
        ('ds', 'Доктор наук'),
        (None, 'Оберіть ступінь'),
    )



    univer = models.CharField(max_length=100, verbose_name='Навчальний заклад')
    spec = models.CharField(max_length=50, verbose_name='Спеціальність')
    degree = models.CharField(max_length=6, verbose_name='Ступінь освіти', choices=KIND_L)
    about = models.TextField(verbose_name='Головне')
    date_start = models.IntegerField(verbose_name='З', choices=YEAR_CHOICES)
    date_over = models.IntegerField(verbose_name='По', choices=YEAR_CHOICES)

    objects = models.Manager()

    class Meta:
        verbose_name = 'Освіта'
        verbose_name_plural = 'Освіти'
        ordering = ['-date_over']

    def __str__(self):
        return self.univer


class WorkPlaces(models.Model):
    firma = models.CharField(max_length=50, verbose_name='Компанія')
    prof = models.CharField(max_length=50, verbose_name='Спеціальність')
    about = models.TextField(verbose_name='Головне')
    date_start = models.IntegerField(verbose_name='З', choices=YEAR_CHOICES)
    date_over = models.IntegerField(verbose_name='По', choices=YEAR_CHOICES)

    objects = models.Manager()

    class Meta:
        verbose_name = 'Місце роботи'
        verbose_name_plural = 'Місця роботи'
        ordering = ['-date_over']

    def __str__(self):
        return self.firma


class Skills(models.Model):
    skill = models.CharField(max_length=50, verbose_name='Вміння')
    shortly = models.TextField(verbose_name='Стисло')
    stages = models.ManyToManyField('SkillHistory', verbose_name='Етап розвитку', related_query_name='stages')
    logo = models.ImageField(upload_to="logo/", verbose_name="Значок", null=True)


    objects = models.Manager()

    class Meta:
        verbose_name = 'Вміння'
        verbose_name_plural = 'Вміння'
        ordering = ['skill']

    def __str__(self):
        return self.skill


class SkillHistory(models.Model):
    stage = models.CharField(max_length=50, verbose_name='Етап розвитку')
    about = models.TextField(verbose_name='Головне')
    date_start = models.IntegerField(verbose_name='З', choices=YEAR_CHOICES)
    date_over = models.IntegerField(verbose_name='По', choices=YEAR_CHOICES)

    objects = models.Manager()

    class Meta:
        verbose_name = 'Стадія розвитку вміння'
        verbose_name_plural = 'Стадії розвитку вмінь'
        ordering = ['-date_over', 'stage']

    def __str__(self):
        return self.stage


class Portfolio(models.Model):
    name = models.CharField(max_length=50, verbose_name='Назва проекту')
    teh = models.CharField(max_length=50, verbose_name='Технологія')
    url = models.CharField(max_length=50, verbose_name='GitHub посилання')
    pic = models.ImageField(upload_to="portfolio/", verbose_name="Картинка портфоліо")

    objects = models.Manager()

    class Meta:
        verbose_name = 'Портфоліо'
        verbose_name_plural = 'Портфоліо'
        ordering = ['name']

    def __str__(self):
        return self.name


class WhyMe(models.Model):
    type = models.CharField(max_length=50, verbose_name='Персональна якість')
    about = models.TextField(verbose_name='Докладніше')
    pic = models.ImageField(upload_to="why_me/", verbose_name="Картинка якості", null=True)

    objects = models.Manager()

    class Meta:
        verbose_name = 'Якості'
        verbose_name_plural = 'Якості'
        ordering = ['type']

    def __str__(self):
        return self.type

my_site/site_app/forms.py
from django import forms
from django.forms import ModelForm, TextInput, EmailInput

from .models import MainInfo
# FIO = 'Савушкін Віталій'
FIO = 'Savushkin Vitalii'


class ContactForm(forms.Form):
    if FIO == 'Савушкін Віталій':
        name = forms.CharField(label='Ім\'я', max_length=50,
                           widget=TextInput(
                               attrs={'class': 'form-control', 'placeholder': "ІМ\'Я", 'style': 'font-size: 14px'}))
        email = forms.EmailField(label='Email', max_length=150,
                             widget=EmailInput(attrs={'class': 'form-control', 'placeholder': "ВАША ПОШТОВА СКРИНЬКА",
                                                      'style': 'font-size: 14px'}))
        message = forms.CharField(label='Повідомлення', max_length=5000,
                              widget=forms.Textarea(
                                  attrs={'size': 100, 'class': 'form-control', 'placeholder': "ПОВІДОМЛЕННЯ",
                                         'style': 'font-size: 14px'}))
    else:
        name = forms.CharField(label='Ім\'я', max_length=50,
                               widget=TextInput(
                                   attrs={'class': 'form-control', 'placeholder': "NAME", 'style': 'font-size: 14px'}))
        email = forms.EmailField(label='Email', max_length=150,
                                 widget=EmailInput(
                                     attrs={'class': 'form-control', 'placeholder': "EMAIL",
                                            'style': 'font-size: 14px'}))
        message = forms.CharField(label='Повідомлення', max_length=5000,
                                  widget=forms.Textarea(
                                      attrs={'size': 100, 'class': 'form-control', 'placeholder': "MESSAGE",
                                             'style': 'font-size: 14px'}))

my_site/site_app/views.py
from django.http import FileResponse
from django.shortcuts import render, redirect
from django.core.mail import BadHeaderError, send_mail
from django.http import HttpResponse
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages

# Create your views here.
from django.views.generic import ListView

from .forms import ContactForm
from .models import *
FIO = 'Савушкін Віталій'
CONTEXT = {}
CONTEXT['information'] = MainInfo.objects.filter(fio=FIO)
CONTEXT['location_sity'] = Locations_Sity.objects.filter(info__fio=FIO)
CONTEXT['location_country'] = Locations_Country.objects.filter(info__fio=FIO)
CONTEXT['langs'] = Languages.objects.filter(info__fio=FIO)
CONTEXT['interests'] = Interests.objects.filter(info__fio=FIO)
CONTEXT['workhour'] = WorkHours.objects.filter(info__fio=FIO)
CONTEXT['whyme'] = WhyMe.objects.filter(info__fio=FIO)
CONTEXT['educations'] = Educations.objects.filter(info__fio=FIO)
CONTEXT['workplaces'] = WorkPlaces.objects.filter(info__fio=FIO)
CONTEXT['skills'] = Skills.objects.filter(info__fio=FIO)


def index(request):

    context = {}
    context.update(CONTEXT)

    return render(request, 'site_app/index.html', context=context)


def download_cv(request):
    from pathlib import Path
    # Build paths inside the project like this: BASE_DIR / 'subdir'.
    BASE_DIR = Path(__file__).resolve().parent.parent
    filename = Path(BASE_DIR, 'site_app/static/site_app/cv', 'Savushkin_CV.pdf')
    if not filename.exists():
        filename = Path(BASE_DIR, 'static/site_app/cv', 'Savushkin_CV.pdf')

    return FileResponse(open(filename, 'rb'), as_attachment=True)


class SkillsView(ListView):
    model = Skills
    template_name = 'site_app/skills.html'
    context_object_name = 'skills'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(CONTEXT)
        return context

    def get_queryset(self):
        return Skills.objects.filter(info__fio=FIO)


class ContactsView(ListView, SuccessMessageMixin):
    model = MainInfo
    template_name = 'site_app/contacts.html'
    context_object_name = 'contacts'
    success_message = 'Ваш лист успішно відправлено'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(CONTEXT)
        context['form'] = ContactForm()

        return context

    def get_queryset(self):
        return MainInfo.objects.filter(fio=FIO)

    def post(self, request):
        if request.method == 'POST':
            form = ContactForm(request.POST)
            if form.is_valid():
                messages.success(request, 'Ваш лист успішно відправлено')
                subject = "From Resume_Site"
                body = {

                    'name': f"Відправник: {form.cleaned_data['name']}",
                    'email': f"Скринька відправника: {form.cleaned_data['email']}",
                    'text': 'Текст повідомлення: ',
                    'message': form.cleaned_data['message'],
                }
                message = "\n".join(body.values())
                try:
                    send_mail(subject, message,
                               'vivog2022@ukr.net',
                              ['vivog2022@ukr.net'], fail_silently=False)
                except BadHeaderError:
                    return HttpResponse('Знайдено невірний заголовок')
                return redirect("site_app:contacts")

        form = ContactForm()
        return render(request, "site_app/contacts.html", {'form': form})


def portfolio(request):

    portfolio = Portfolio.objects.all()
    context = {
        'portfolio': portfolio,
    }
    context.update(CONTEXT)

    return render(request, 'site_app/portfolio.html', context=context)

my_site/site_app/templates/site_app/base.html
    <!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% block title %}
    <title>Savushkin::Resume</title>
    {% endblock %}
    {% load static %}
    {% load i18n %}
    {% load static i18n %}
    <link href="https://fonts.googleapis.com/css?family=Mukta:300,400,500,600,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'site_app/vendors/@fortawesome/fontawesome-free/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'site_app/css/live-resume.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'site_app/images/icon.ico' %}"/>


    </style>
</head>

<body>
          {% block lang %}
          {% load i18n %}
          <div style="text-align: right">
          <form action="{% url 'set_language' %}" method="post">
              {% csrf_token %}
              {% get_current_language as LANGUAGE_CODE %}
              {% get_available_languages as LANGUAGES %}
              {% for language in LANGUAGES %}
              {% if language.0 != LANGUAGE_CODE %}
              <button type="submit" name="language" value="{{ language.0 }}"
                      class="btn btn-primary btn-hire-me">
                  {{ language.1 }}
              </button>
              {% endif %}
              {% endfor %}
          </form>
          </div>
        {% endblock lang %}
    <header>
        {% block nav %}
        <nav class="collapsible-nav" id="collapsible-nav">
            <a href="{% url 'site_app:index' %}" class="nav-link active">{% trans "ГОЛОВНА" %}</a>
            <a href="{% url 'site_app:skills' %}" class="nav-link">{% trans "ВМІННЯ" %}</a>
            <a href="{% url 'site_app:portfolio' %}" class="nav-link">{% trans "ПОРТФОЛІО" %}</a>
            <a href="{% url 'site_app:contacts' %}" class="nav-link">{% trans "ЗВ'ЯЗОК" %}</a>
        </nav>
        <button class="btn btn-menu-toggle btn-white rounded-circle" data-toggle="collapsible-nav"
            data-target="collapsible-nav"><img src="{% static 'site_app/images/hamburger.svg' %}" alt="hamburger"></button>

        {% endblock %}
    </header>
    <div class="content-wrapper">
        <aside>
            {% for info in information %}
            <div class="profile-img-wrapper">
                <img src="{{ info.photo.url }}" alt="profile">
            </div>
            <h1 class="profile-name">{{ info.fio|upper }}</h1>
            <div class="text-center">
                <span class="badge badge-white badge-pill profile-designation">{{ info.position|upper }}</span>
            </div>
            <nav class="social-links">
                <a target="_blank" href="https://www.facebook.com/profile.php?id=100012944310452" class="social-link"><i class="fab fa-facebook-f"></i></a>
                <a target="_blank" href="https://www.linkedin.com/feed/?trk=homepage-basic_google-one-tap-submit" class="social-link"><i class="fab fa-linkedin"></i></a>
                <a target="_blank" href="https://github.com/Vivog?tab=repositories/" class="social-link"><i class="fab fa-github"></i></a>
           </button>
            </nav>
            <div class="widget">
                <h5 class="widget-title"><strong>{% trans "ОСОБИСТА ІНФОРМАЦІЯ" %}:</strong></h5>
                <div class="widget-content">
                    <p><span>{% trans "ДАТА НАРОДЖЕННЯ" %}: </span>{{ info.birthday }}</p>
                    <p><span>{% trans "ТЕЛЕФОН" %}: </span><a style="color: black" href="{% url 'site_app:contacts' %}">{{ info.phone }}</a></p>
                    <p><span>{% trans "ПОШТА" %}: </span><a style="color: black" href="{% url 'site_app:contacts' %}">{{ info.email }}</a></p>
                    <p><span>{% trans "РОЗТАШУВАННЯ" %}:  </span><a target="_blank" style="color: black" href="https://www.google.com/maps/place/%D0%9D%D0%B8%D0%BA%D0%BE%D0%BB%D0%B0%D0%B5%D0%B2,+%D0%9D%D0%B8%D0%BA%D0%BE%D0%BB%D0%B0%D0%B5%D0%B2%D1%81%D0%BA%D0%B0%D1%8F+%D0%BE%D0%B1%D0%BB%D0%B0%D1%81%D1%82%D1%8C,+%D0%A3%D0%BA%D1%80%D0%B0%D0%B8%D0%BD%D0%B0,+54000/@46.974009,31.99491,14z/data=!4m5!3m4!1s0x40c5cb89fb7213d5:0xc85f820a74a1e13c!8m2!3d46.975033!4d31.9945829?hl=ru-RU">{{ location_sity.0}}, {{location_country.0}}</a></p>
                    <button class="btn btn-download-cv btn-primary rounded-pill"> <img src="{% static 'site_app/images/download.svg' %}" alt="download"
                        class="btn-img"><a href="{% url 'site_app:downloadcv' %}" style="color: white">{% trans "ЗАВАНТАЖИТИ CV" %}</a></button>
                </div>
            </div>
            <div class="widget card">
                <div class="card-body">
                    <div class="widget-content">
                        <h5 class="widget-title card-title"><strong>{% trans "МОВИ" %}: </strong></h5>
                        {% for l in langs %}
                        <p>{{ l.get_language_display|upper }}: {{ l.get_level_display|upper }}</p>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="widget card">
                <div class="card-body">
                    <div class="widget-content">
                        <h5 class="widget-title card-title"><strong>{% trans "ЗАХОПЛЕННЯ" %}:</strong></h5>
                        {% for i in interests %}
                        <p>{{ i.interest|upper }}</p>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </aside>
        <main>
        {% block content %} {% endblock content%}
            {% block carusel %}

             <section class="testimonial-section">
                <div id="testimonialCarousel" class="testimonial-carousel carousel slide" data-ride="carousel">
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <p style="font-size: 12px; max-width: 350px; height: 50px" class="testimonial-content">{{ whyme.0.about }}</p>
                            <img src="{{ whyme.0.pic.url }}" style="width: 40px; height: 40px" alt="profile" class="testimonial-img">
                            <p style="font-size: 14px" class="testimonial-name">{{ whyme.0.type }}</p>
                        </div>
                         {% for wm in whyme|slice:'1:' %}
                        <div class="carousel-item">
                            <p style="font-size: 12px; max-width: 350px; height: 50px" class="testimonial-content">{{wm.about}}</p>
                            <img src="{{ wm.pic.url }}" style="width: 40px; height: 40px" alt="profile" class="testimonial-img">
                            <p style="font-size: 14px" class="testimonial-name">{{wm.type}}</p>
                        </div>
                        {% endfor %}
                    </div>
                    <ol class="carousel-indicators">
                        <li data-target="#testimonialCarousel" data-slide-to="0" class="active"></li>
                        <li data-target="#testimonialCarousel" data-slide-to="1"></li>
                        <li data-target="#testimonialCarousel" data-slide-to="2"></li>
                    </ol>
                </div>
            </section>

            {% endblock %}

<!--            endfor of information-->
            {% endfor %}

            <footer>{% trans "Власне резюме. Усі права захищено 2022" %}</footer>
        </main>
    </div>
    <script src="{% static 'site_app/vendors/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'site_app/vendors/@popperjs/core/dist/umd/popper-base.min.js' %}"></script>
    <script src="{% static 'site_app/vendors/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'site_app/js/live-resume.js' %}"></script>
</body>

</html>

my_site/site_app/templates/site_app/contacts.html
{% extends 'site_app/base.html' %}
{% load static %}
{% load static i18n %}
{% block title %}
<title>Savushkin::Contacts</title>
{% endblock %}
{% block nav %}
<nav class="collapsible-nav" id="collapsible-nav">
    <a href="{% url 'site_app:contacts' %}" class="nav-link active">{% trans "ЗВ'ЯЗОК" %}</a>
    <a href="{% url 'site_app:index' %}" class="nav-link">{% trans "ГОЛОВНА" %}</a>
    <a href="{% url 'site_app:skills' %}" class="nav-link">{% trans "ВМІННЯ" %}</a>
    <a href="{% url 'site_app:portfolio' %}" class="nav-link">{% trans "ПОРТФОЛІО" %}</a>
</nav>
<button class="btn btn-menu-toggle btn-white rounded-circle" data-toggle="collapsible-nav"
        data-target="collapsible-nav"><img src="{% static 'site_app/images/hamburger.svg' %}" alt="hamburger"></button>
{% endblock %}
<!--main info section-->
{% block content %}
<section class="contact-section">
    <h2 class="section-title">{% trans "Зв'яжись зі мною" %}</h2>
    <p style="font-size: 14px" class="mb-4">
        {% trans "Якщо ви бажаете запропонувати мені роботу, або переговорити з будь-яких питань, то зв'яжиться зі мною" %}</p>
    {% for info in information %}
    <div class="contact-cards-wrapper">
        <div class="contact-card">
            <h6 class="contact-card-title">{% trans "Зателефонуйте мені" %}</h6>
            <p style="font-size: 14px" class="contact-card-content">{{ info.phone }}</p>
        </div>
        <div class="contact-card">
            <h6 class="contact-card-title">{% trans "Надсилайте мені email" %}</h6>
            <p style="font-size: 14px" class="contact-card-content">{{ info.email }}</p>
        </div>
    </div>
    <form method="post" class="contact-form" action="{% url 'site_app:contacts' %}">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="form-group form-group-name">
            {{ form.name.errors }}
            <label for="{{ form.name.id_for_label }}" class="sr-only">{% trans "ІМ'Я" %}</label>
            {{form.name}}
        </div>
        <div class="form-group form-group-email">
            {{ form.email.errors }}
            <label for="{{ form.email.id_for_label }}" class="sr-only">{% trans "ПОШТОВА СКРИНЬКА" %}</label>
            {{form.email}}
        </div>
        <div class="form-group">
            {{ form.message.errors }}
            <label for="{{form.message.id_for_label}}" class="sr-only">{% trans "ПОВІДОМЛЕННЯ" %}</label>
            {{form.message}}
        </div>
        <button type="submit" class="btn btn-primary form-submit-btn">{% trans "НАДІСЛАТИ" %}</button>
    </form>
    {% endfor %}
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li
        {% if message.tags %} class='{{ message.tags }}'{% endif %}>
        {{ message }}
        </li>
        {% endfor %}
    </ul>
    {% endif %}
</section>


<section class="location-section">
    <h5 class="section-title">{% trans "Я ось тут" %}</h5>

    <div class="map-wrapper embed-responsive embed-responsive-16by9">
        <iframe src="https://maps.google.com/maps?width=600&amp;height=400&amp;hl={% trans 'ua' %}&amp;q=Mykolaiv&amp;t=&amp;z=14&amp;ie=UTF8&amp;iwloc=B&amp;output=embed"
                width="600" height="450" frameborder="0" style="border:0;" allowfullscreen=""
                class="embed-responsive-item"></iframe>
    </div>
</section>

{% endblock %}
<!--main info section-->

my_site/site_app/templates/site_app/portfolio.html
{% extends 'site_app/base.html' %}
{% load static %}
{% load static i18n %}
    {% block title %}
    <title>Savushkin::PortFolio</title>
    {% endblock %}
{% block nav %}
<nav class="collapsible-nav" id="collapsible-nav">
    <a href="{% url 'site_app:portfolio'%}" class="nav-link active">{% trans 'ПОРТФОЛІО' %}</a>
    <a href="{% url 'site_app:index' %}" class="nav-link">{% trans 'ГОЛОВНА' %}</a>
    <a href="{% url 'site_app:skills' %}" class="nav-link">{% trans 'ВМІННЯ' %}</a>
    <a href="{% url 'site_app:contacts' %}" class="nav-link">{% trans "ЗВ'ЯЗОК" %}</a>
</nav>
<button class="btn btn-menu-toggle btn-white rounded-circle" data-toggle="collapsible-nav"
        data-target="collapsible-nav"><img src="{% static 'site_app/images/hamburger.svg' %}" alt="hamburger"></button>
{% endblock %}

{% block content %}
<section class="portfolio-section">
                <h2 class="section-title">{% trans 'ПОРТФОЛІО' %}</h2>
                <div class="portfolio-wrapper">
                    {% for port in portfolio %}
                    <figure style="width: calc(50% - 5.5px); height: 400px" class="portfolio-item hover-box">
                        <a href="{{port.url}}" target="_blank">
                            <img src={{port.pic.url}} alt="project" class="portfolio-item-img"
                                 style="max-width: 90%; max-height: 80%; margin: 5% 5% 5% 5%;"></a>
                        <figcaption class="portfolio-item-details overlay">
                            <h5 class="portfolio-item-title">{{port.name}}</h5>
                            <p class="portfolio-item-description">{{port.teh}}</p>
                        </figcaption>
                    </figure>
                    {% endfor %}
                </div>
            </section>
{% endblock %}
<!--main info section-->